FROM python:3.10-slim AS build

RUN apt-get update && apt-get install -y build-essential curl
ENV VIRTUAL_ENV=/opt/venv \
    PATH="/opt/venv/bin:$PATH"

ADD https://astral.sh/uv/install.sh /install.sh
RUN chmod -R 655 /install.sh && /install.sh && rm /install.sh
COPY requirements.txt .
RUN /root/.cargo/bin/uv venv /opt/venv && \
    /root/.cargo/bin/uv pip install --no-cache -r ./requirements.txt

FROM python:3.10-slim

COPY --from=build /opt/venv /opt/venv
ENV PATH="/opt/venv/bin:$PATH"

WORKDIR /app

COPY *.py /app/src/weatherman/
COPY api/ /app/src/weatherman/api/

EXPOSE 5000
ENV PYTHONPATH="/app"
CMD ["python", "-m", "uvicorn", "src.weatherman.api.main:app", "--port", "5000", "--host", "0.0.0.0"]